apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-pedido-app
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://rds-fiap-tech-challenge.cbl891k9286k.us-east-1.rds.amazonaws.com:3306/pedidodb
  SPRING_JPA_SHOW: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  AWS_SQS_URI: https://sqs.us-east-1.amazonaws.com/797459365217/lanchonete-producao-queue.fifo
  ENVIO_PEDIDO_PRODUCAO_ENABLED: "true"
  URI_API_PAGAMENTO: http://svc-pagamento-app/pagamento-app/pagamentos
