apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-app
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://rds-fiap-tech-challenge.cbl891k9286k.us-east-1.rds.amazonaws.com:3306/pedidodb
  SPRING_JPA_SHOW: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  AWS_SQS_URI: https://sqs.us-east-1.amazonaws.com/797459365217/teste.fifo
  AWS_ACCESSKEYID: ASIA3TLCIHVQQS52XH7R
  AWS_SECRETACCESSKEY: Jlj7gpKqOUMYCyGu0BI7UQtmUA58LmGTWRMNGKIW
  AWS_SESSIONTOKEN: IQoJb3JpZ2luX2VjELH//////////wEaCXVzLXdlc3QtMiJGMEQCIB76yqVTY3NaCoD3ITPIDj9VBXf6LxRkHRgUO97HORKQAiBFfu74SfkRcxfLJebU7lcxVn00hGBwUHjguvBprGyKmiqtAggaEAEaDDc5NzQ1OTM2NTIxNyIMZ3f5OPUOTd+HJJciKooCU7sUcySGPV5XlshrQ+/N0ZBfKslZxeG9YaEOSX7dByFvWB2lzdXzYYcNs5h8APT7yVr+XLlGxhm+a+ZZJyoM4ciOGG6VXC+hRgPkCyksrg/Qx6vgR59PxJ1k5PwhAYQ/IS1vpUTgTI5lYWRYeUiQ/xPzm9lO0cy9kvEUTVAYR7QOz2zvd5joXh0V43OizawYj63eZJNGMgk/pfwgeqK+4i42poo7+5MryhuniHAhg49sJhZWJ7I87+xWvkC9Ml51BTM1VGKabToYQtLWITtYGJQ0NSEWgdnCl1G8KPGXjs5sMbF4b3KhRewBvVFcAfRf74oirj/sdzshxgXXBDL9CmPPK9W4x5rmaV4wlYn0sQY6ngFuWTrIbDpKnpF78fO2zFz69vTIOlTwuE42+dGbRbfQCZsUJZ7tPLBjmeaxg5yeA5F+bwbt1zuM80G3P7cw7Z5lk1McP0/jt/Ey3Yg55tBHFB/yZysFl+N2RaZsoDjYqGnIgs8+uUja/HgUv1NtoaEiTwhF8ii8B9m8UDm39pRd0vZmvuYjUX26zGfKkT34dmxh4rUeTg6OMbs5Zh58Iw==
