apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pedido-deployment
  labels:
    app: app-pedido-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-pedido-pod
  template:
    metadata:
      name: app-pedido-pod
      labels:
        app: app-pedido-pod
    spec:
      containers:
        - name: pedido-app
          image: thiagobsn/pedido-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: password
            - name: SPRING_JPA_SHOW
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: SPRING_JPA_SHOW
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
            - name: AWS_SQS_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: AWS_SQS_URI
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: AWS_SESSION_TOKEN
            - name: ENVIO_PEDIDO_PRODUCAO_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: configmap-pedido-app
                  key: ENVIO_PEDIDO_PRODUCAO_ENABLED
          livenessProbe:
            httpGet:
              path: /pedido-app/actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              cpu: 500m
              memory: 256Mi
      